import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. Importações da Sonner
import { Toaster as SonnerToaster } from "sonner";

// 2. Importações da React-Toastify
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <video
            autoPlay
            loop
            muted
            playsInline
            className="fixed inset-0 w-full h-full object-cover -z-10 pointer-events-none"
        >
            <source src="/back.mp4" type="video/mp4" />
        </video>

        <div className="fixed inset-0 bg-black/60 -z-10 pointer-events-none" />

        <main className="relative min-h-screen">
            {children}
        </main>

        <SonnerToaster position="top-right" richColors closeButton  />

        <ToastContainer
            position="bottom-right"
            theme="dark"
            autoClose={3500}
        />
        </body>
        </html>
    );
}